Repository AY2021S1-CS2113T-T09-4/tp, pull requests merged in 2020-10, with the labels that each got.

#12 owen - calorielist
  src/main/java/seedu/duke/ActivityList.java
  src/main/java/seedu/duke/ActivityMap.java
  src/main/java/seedu/duke/Duke.java
Labels: priority.High

#34 added find function
  src/main/java/seedu/duke/ActivityList.java
  src/main/java/seedu/duke/Duke.java
Labels: priority.High, type.Story

#43 #17 and #13
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/storage/Userinfotextfilestorage.java
  src/main/java/seedu/duke/userprofile/Initialiseuser.java
  src/main/java/seedu/duke/userprofile/Userinfo.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#59 Create User interface
  src/main/java/seedu/duke/Activity.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Exercise.java
  src/main/java/seedu/duke/Food.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddExerciseCommand.java
  src/main/java/seedu/duke/command/AddFoodCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/ListCommand.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Story

#64 Implement JUnit test for add command fixes #38
  src/main/java/seedu/duke/Food.java
  src/test/java/seedu/duke/ActivityAddTest.java
Labels: type.Test

#65 add ExceptionMessages class
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/ExceptionMessages.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
Labels: type.Task

#63 Added list activities for specific dates, added J-Unit tests for adding activities into different dates, slapped listCommand and toString methods to simplify things
  src/main/java/seedu/duke/ActivityList.java
  src/main/java/seedu/duke/DayMap.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/ExceptionMessages.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/test/java/seedu/duke/ActivityListTest.java
  src/test/java/seedu/duke/DayMapTest.java
Labels: type.Task, type.Test

#66 update find function
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/command/FindCalorieCommand.java
  src/main/java/seedu/duke/command/FindDescriptionCommand.java
Labels: priority.High, type.Story

#72 Catch exception for Add Activity
  src/main/java/seedu/duke/ExceptionMessages.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/command/HelpCommand.java
Labels: priority.Medium, type.Bug

#77 Organise and update help command
  src/main/java/seedu/duke/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Story

#96 Implement date to add command
  src/main/java/seedu/duke/ActivityList.java
  src/main/java/seedu/duke/DayMap.java
  src/main/java/seedu/duke/ExceptionMessages.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddExerciseCommand.java
  src/main/java/seedu/duke/command/AddFoodCommand.java
  src/main/java/seedu/duke/command/ByeCommand.java
  src/main/java/seedu/duke/command/EditExerciseCommand.java
  src/main/java/seedu/duke/command/EditFoodCommand.java
  src/main/java/seedu/duke/command/FindCalorieCommand.java
  src/main/java/seedu/duke/command/FindDescriptionCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/test/java/seedu/duke/ActivityEditTest.java
Labels: priority.High, type.Enhancement

#98 Developer guide - add user stories and problems addressed
  docs/DeveloperGuide.md
Labels: priority.High, type.DeveloperGuide

#99 User Guide - add base code + some features
  docs/UserGuide.md
Labels: priority.High, type.UserGuide

#104 Adding features into user guide
  docs/UserGuide.md
Labels: type.UserGuide

#105 create save repeated set to new file - but not separated commands yet
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/ExceptionMessages.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/command/AddNewRepeatedSet.java
  src/main/java/seedu/duke/command/CreateNewUserCommand.java
  src/main/java/seedu/duke/storage/UserSetStorage.java
Labels: Work-In-Progress

#108 Chain commands
  docs/UserGuide.md
  docs/_config.yml
  src/main/java/seedu/duke/ActivityList.java
  src/main/java/seedu/duke/DayMap.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/command/EditExerciseCommand.java
  src/main/java/seedu/duke/command/EditFoodCommand.java
Labels: priority.Medium

#111 Create a set of entries
  src/main/java/seedu/duke/storage/UserSetStorage.java
  test2.txt
Labels: Work-In-Progress, type.Task

#114 edit user guide for find
  docs/UserGuide.md
Labels: type.UserGuide

#112 implement find by multiple keywords
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/command/FindAllCommand.java
  src/main/java/seedu/duke/command/FindEitherCommand.java
Labels: priority.Medium

#121 troubleshooting and correcting error messages
  docs/UserGuide.md
  src/main/java/seedu/duke/ActivityList.java
  src/main/java/seedu/duke/DayMap.java
  src/main/java/seedu/duke/ExceptionMessages.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddExerciseCommand.java
  src/main/java/seedu/duke/command/AddFoodCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditExerciseCommand.java
  src/main/java/seedu/duke/command/EditFoodCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/MoveActivityCommand.java
  src/test/java/seedu/duke/ActivityAddTest.java
  src/test/java/seedu/duke/ActivityEditTest.java
Labels: priority.Medium

#123 Update user guide
  docs/UserGuide.md
  src/main/java/seedu/duke/Ui.java
Labels: type.UserGuide

#124 update user guide
  docs/UserGuide.md
Labels: type.UserGuide

#129 update find functions with last seen
  src/main/java/seedu/duke/DayMap.java
  src/main/java/seedu/duke/command/FindAllCommand.java
  src/main/java/seedu/duke/command/FindCalorieCommand.java
  src/main/java/seedu/duke/command/FindDescriptionCommand.java
  src/main/java/seedu/duke/command/FindEitherCommand.java
  src/test/java/seedu/duke/AdvancedListingTest.java
Labels: priority.High, type.Enhancement

#134 Troubleshooting
  docs/UserGuide.md
  src/main/java/seedu/duke/logic/Parser.java
  src/main/java/seedu/duke/ui/ExceptionMessages.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/userprofile/Initialiseuser.java
  src/main/java/seedu/duke/userprofile/Userinfo.java
Labels: priority.High, type.UserGuide

#136 troubleshoot + edit UG + remove magic numbers
  docs/UserGuide.md
  src/main/java/seedu/duke/command/AddExerciseCommand.java
  src/main/java/seedu/duke/command/AddFoodCommand.java
  src/main/java/seedu/duke/command/EditExerciseCommand.java
  src/main/java/seedu/duke/command/EditFoodCommand.java
  src/main/java/seedu/duke/logic/Parser.java
  src/main/java/seedu/duke/ui/ExceptionMessages.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.Medium, type.UserGuide

#138 Troubleshooting chain command, add JavaDoc, remove magic number
  docs/UserGuide.md
  src/main/java/seedu/duke/Trakcal.java
  src/main/java/seedu/duke/command/AddExerciseCommand.java
  src/main/java/seedu/duke/command/AddFoodCommand.java
  src/main/java/seedu/duke/command/CreateNewRepeatedSet.java
  src/main/java/seedu/duke/command/CreateNewUserCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditExerciseCommand.java
  src/main/java/seedu/duke/command/EditFoodCommand.java
  src/main/java/seedu/duke/command/FindAllCommand.java
  src/main/java/seedu/duke/command/FindDescriptionCommand.java
  src/main/java/seedu/duke/command/FindEitherCommand.java
  src/main/java/seedu/duke/command/GraphCommand.java
  src/main/java/seedu/duke/command/InvalidCommand.java
  src/main/java/seedu/duke/logic/Parser.java
  src/main/java/seedu/duke/model/Activity.java
  src/main/java/seedu/duke/model/ActivityList.java
  src/main/java/seedu/duke/model/DayMap.java
  src/main/java/seedu/duke/model/Exercise.java
  src/main/java/seedu/duke/model/Food.java
  src/main/java/seedu/duke/model/GraphDrawing.java
  src/main/java/seedu/duke/model/GraphProperty.java
  src/main/java/seedu/duke/model/ListDrawer.java
  src/main/java/seedu/duke/ui/ExceptionMessages.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: Work-In-Progress, priority.Medium

#142 update UG
  docs/UserGuide.md
  src/main/java/seedu/duke/ui/Ui.java
Labels: Work-In-Progress, type.UserGuide

#146 Update User guide
  docs/UserGuide.md
Labels: type.UserGuide

#155 add image
  docs/diagrams/AddFoodFeature.jpg
  docs/diagrams/ChainCommandFeature.jpg
  docs/diagrams/EditActivityFeature.jpg
Labels: type.DeveloperGuide

#158 Developer Guide
  docs/DeveloperGuide.md
Labels: type.DeveloperGuide

#160 Developer Guide
  docs/DeveloperGuide.md
Labels: type.DeveloperGuide

#159 Developerguide
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.png
  docs/diagrams/ListSequenceDiagram.png
Labels: type.DeveloperGuide

#173 update ToC
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.DeveloperGuide, type.UserGuide
